"""Generate a frontend self-hosting bytecode demo.

The generated bytecode is meant to be executed directly by dao/dao_core.c.
It loads the .ku lexer, parser, and compiler, then runs:

    lex(source) -> parse_tokens(tokens) -> compile_ast(ast) -> run_bytecode(bytecode)

The source mirrors the semantic_core.ku node shape so the C VM frontend path
exercises a standard-library-like thought, dict mutation, list literals,
escaped newlines, and string literals.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from dao.runtime import DaoEnv, Thought  # noqa: E402
from dao.dao_lexer import lex as py_lex  # noqa: E402
from dao.dao_parser import parse_tokens as py_parse_tokens  # noqa: E402


OUT = ROOT / "demos" / "frontend_compile_demo.kub.json"
SOURCE = (
    "思 语义_节点(类型, 值, 子节点) {\n"
    "  节点 = {}\n"
    '  节点["type"] = 类型\n'
    '  节点["value"] = 值\n'
    '  节点["children"] = 子节点\n'
    "  节点\n"
    "}\n"
    '语义_节点("literal", "x", [])'
)


def lit(value):
    return {"type": "literal", "value": value}


def ref(name):
    return {"type": "ref", "value": name}


def assign(name, value):
    return {"type": "assign", "value": name, "children": [value]}


def block(*children):
    return {"type": "block", "children": list(children)}


def call_node(name, *args):
    return {"type": "call", "value": name, "children": list(args)}


def parse_file(path: Path):
    source = path.read_text(encoding="utf-8")
    tokens = py_lex(source)
    tokens.append({"type": "eof", "value": "", "line": 0, "col": 0, "pos": 0})
    return py_parse_tokens(tokens)


def load_frontend():
    Thought.registry.clear()
    env = DaoEnv()
    env.load(str(ROOT / "dao" / "std" / "lexer.ku"))
    env.load(str(ROOT / "dao" / "std" / "parser.ku"))
    env.load(str(ROOT / "dao" / "std" / "compiler.ku"))


def build_demo_ast():
    ast = {"type": "block", "children": []}
    for module_name in ("lexer.ku", "parser.ku", "compiler.ku"):
        ast["children"].extend(parse_file(ROOT / "dao" / "std" / module_name)["children"])
    ast["children"].append(
        block(
            assign("source", lit(SOURCE)),
            assign("tokens", call_node("lex", ref("source"))),
            assign("ast", call_node("parse_tokens", ref("tokens"))),
            assign("bytecode", call_node("compile_ast", ref("ast"))),
            call_node("run_bytecode", ref("bytecode")),
        )
    )
    return ast


def main():
    load_frontend()
    bytecode = Thought.registry["compile_ast"].call([build_demo_ast()])
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(bytecode, ensure_ascii=False, separators=(",", ":")) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    print(f"{len(bytecode['constants'])} constants, {len(bytecode['instructions'])} instructions")


if __name__ == "__main__":
    main()
