"""Generate frontend bootstrap bytecode for the C VM.

The generated bytecode only loads the .ku lexer, parser, and compiler
definitions. dao_core can then reuse those definitions to compile and run
an external .ku source file via:

    dao_core --bootstrap demos/frontend_bootstrap.kub.json program.ku

Prefer the C VM path: use the existing committed bootstrap image to run
``dao/std/bootstrap.ku`` and produce a candidate image from inside the VM.
The candidate must pass smoke tests before replacing the committed fixture.
If a local C toolchain/WSL is unavailable, or the candidate is not yet
self-hosting-clean, fall back to the Python harness.
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
import tempfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from dao.runtime import DaoEnv, Thought  # noqa: E402
from dao.dao_lexer import lex as py_lex  # noqa: E402
from dao.dao_parser import parse_tokens as py_parse_tokens  # noqa: E402


OUT = ROOT / "demos" / "frontend_bootstrap.kub.json"
FRONTEND_MODULES = ("lexer.ku", "parser.ku", "compiler.ku")


SMOKE_SOURCE = """思 加一(数) {
  数 + 1
}
加一(41)
"""

RICH_SMOKE_SOURCE = """思 求和二(左, 右) {
  左 + 右
}
列表 = [1, 2, 3]
字典 = {"a": 求和二(1, 2), "b": 列表[2]}
i = 0
总 = 0
当 i < len(列表) {
  总 = 总 + 列表[i]
  i = i + 1
}
{"sum": 总, "dict": 字典}
"""


def to_wsl_path(path: Path) -> str:
    resolved = path.resolve()
    drive = resolved.drive.rstrip(":").lower()
    tail = resolved.relative_to(resolved.anchor).as_posix()
    return f"/mnt/{drive}/{tail}"


def parse_file(path: Path):
    source = path.read_text(encoding="utf-8")
    tokens = py_lex(source)
    tokens.append({"type": "eof", "value": "", "line": 0, "col": 0, "pos": 0})
    return py_parse_tokens(tokens)


def load_compiler():
    Thought.registry.clear()
    env = DaoEnv()
    env.load(str(ROOT / "dao" / "std" / "compiler.ku"))


def build_bootstrap_ast():
    ast = {"type": "block", "children": []}
    for module_name in FRONTEND_MODULES:
        ast["children"].extend(parse_file(ROOT / "dao" / "std" / module_name)["children"])
    return ast


def generate_with_python() -> dict:
    load_compiler()
    bytecode = Thought.registry["compile_ast"].call([build_bootstrap_ast()])
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(bytecode, ensure_ascii=False, separators=(",", ":")) + "\n", encoding="utf-8")
    return bytecode


def smoke_sources(tmpdir: Path) -> list[tuple[Path, str]]:
    simple_path = tmpdir / "frontend_bootstrap_smoke.ku"
    simple_path.write_text(SMOKE_SOURCE, encoding="utf-8")
    rich_path = tmpdir / "frontend_bootstrap_rich_smoke.ku"
    rich_path.write_text(RICH_SMOKE_SOURCE, encoding="utf-8")
    return [(simple_path, "42"), (rich_path, '{"dict": {"b": 3, "a": 3}, "sum": 6}')]


def validate_candidate_posix(binary: Path, candidate: Path, tmpdir: Path) -> bool:
    for source_path, expected in smoke_sources(tmpdir):
        run = subprocess.run(
            [str(binary), "--bootstrap", str(candidate), str(source_path)],
            cwd=ROOT,
            capture_output=True,
            timeout=60,
        )
        if run.returncode != 0:
            return False
        if run.stdout.decode("utf-8", "replace").strip() != expected:
            return False

    nested = tmpdir / "frontend_bootstrap.nested.kub.json"
    regen_source = tmpdir / "regenerate_nested_frontend_bootstrap.ku"
    regen_source.write_text(
        f'输出路径 = "{nested.as_posix()}"\n'
        f'字节码 = 写前端自举字节码("{ROOT.as_posix()}", 输出路径)\n'
        'len(字节码["instructions"])\n',
        encoding="utf-8",
    )
    regen = subprocess.run(
        [str(binary), "--bootstrap", str(candidate), str(ROOT / "dao" / "std" / "bootstrap.ku"), str(regen_source)],
        cwd=ROOT,
        capture_output=True,
        timeout=180,
    )
    if regen.returncode != 0 or not nested.exists():
        return False
    for source_path, expected in smoke_sources(tmpdir):
        run = subprocess.run(
            [str(binary), "--bootstrap", str(nested), str(source_path)],
            cwd=ROOT,
            capture_output=True,
            timeout=60,
        )
        if run.returncode != 0:
            return False
        if run.stdout.decode("utf-8", "replace").strip() != expected:
            return False
    return True


def validate_candidate_wsl(prefix: list[str], binary: Path, candidate: Path, tmpdir: Path) -> bool:
    for source_path, expected in smoke_sources(tmpdir):
        run = subprocess.run(
            prefix + [to_wsl_path(binary), "--bootstrap", to_wsl_path(candidate), to_wsl_path(source_path)],
            cwd=ROOT,
            capture_output=True,
            timeout=60,
        )
        if run.returncode != 0:
            return False
        if run.stdout.decode("utf-8", "replace").strip() != expected:
            return False

    nested = tmpdir / "frontend_bootstrap.nested.kub.json"
    regen_source = tmpdir / "regenerate_nested_frontend_bootstrap.ku"
    regen_source.write_text(
        f'输出路径 = "{to_wsl_path(nested)}"\n'
        f'字节码 = 写前端自举字节码("{to_wsl_path(ROOT)}", 输出路径)\n'
        'len(字节码["instructions"])\n',
        encoding="utf-8",
    )
    regen = subprocess.run(
        prefix
        + [
            to_wsl_path(binary),
            "--bootstrap",
            to_wsl_path(candidate),
            to_wsl_path(ROOT / "dao" / "std" / "bootstrap.ku"),
            to_wsl_path(regen_source),
        ],
        cwd=ROOT,
        capture_output=True,
        timeout=180,
    )
    if regen.returncode != 0 or not nested.exists():
        return False
    for source_path, expected in smoke_sources(tmpdir):
        run = subprocess.run(
            prefix + [to_wsl_path(binary), "--bootstrap", to_wsl_path(nested), to_wsl_path(source_path)],
            cwd=ROOT,
            capture_output=True,
            timeout=60,
        )
        if run.returncode != 0:
            return False
        if run.stdout.decode("utf-8", "replace").strip() != expected:
            return False
    return True


def run_c_vm_generator_posix(tmpdir: Path, candidate: Path) -> bool:
    binary = tmpdir / "dao_core_generate_frontend_bootstrap"
    build = subprocess.run(
        ["gcc", "-o", str(binary), str(ROOT / "dao" / "dao_core.c"), "-lm", "-Wall", "-O2"],
        cwd=ROOT,
        capture_output=True,
        timeout=30,
    )
    if build.returncode != 0:
        return False

    source_path = tmpdir / "generate_frontend_bootstrap_with_c_vm.ku"
    source_path.write_text(
        f'输出路径 = "{candidate.as_posix()}"\n'
        f'字节码 = 写前端自举字节码("{ROOT.as_posix()}", 输出路径)\n'
        'len(字节码["instructions"])\n',
        encoding="utf-8",
    )
    run = subprocess.run(
        [
            str(binary),
            "--bootstrap",
            str(OUT),
            str(ROOT / "dao" / "std" / "bootstrap.ku"),
            str(source_path),
        ],
        cwd=ROOT,
        capture_output=True,
        timeout=180,
    )
    return run.returncode == 0 and candidate.exists() and validate_candidate_posix(binary, candidate, tmpdir)


def run_c_vm_generator_wsl(tmpdir: Path, candidate: Path) -> bool:
    distro = os.environ.get("DAO_WSL_DISTRO", "kali-linux")
    prefix = ["wsl", "-d", distro, "--"]
    binary = tmpdir / "dao_core_generate_frontend_bootstrap"
    build_cmd = (
        f"cd {to_wsl_path(ROOT)} && "
        f"gcc -o {to_wsl_path(binary)} dao/dao_core.c -lm -Wall -O2"
    )
    build = subprocess.run(
        prefix + ["bash", "-lc", build_cmd],
        capture_output=True,
        timeout=30,
    )
    if build.returncode != 0:
        return False

    source_path = tmpdir / "generate_frontend_bootstrap_with_c_vm.ku"
    source_path.write_text(
        f'输出路径 = "{to_wsl_path(candidate)}"\n'
        f'字节码 = 写前端自举字节码("{to_wsl_path(ROOT)}", 输出路径)\n'
        'len(字节码["instructions"])\n',
        encoding="utf-8",
    )
    run = subprocess.run(
        prefix
        + [
            to_wsl_path(binary),
            "--bootstrap",
            to_wsl_path(OUT),
            to_wsl_path(ROOT / "dao" / "std" / "bootstrap.ku"),
            to_wsl_path(source_path),
        ],
        cwd=ROOT,
        capture_output=True,
        timeout=180,
    )
    return run.returncode == 0 and candidate.exists() and validate_candidate_wsl(prefix, binary, candidate, tmpdir)


def generate_with_c_vm() -> bool:
    if not OUT.exists():
        return False
    with tempfile.TemporaryDirectory(prefix="dao_frontend_bootstrap_") as raw_tmpdir:
        tmpdir = Path(raw_tmpdir)
        candidate = tmpdir / "frontend_bootstrap.candidate.kub.json"
        try:
            if os.name == "nt":
                ok = run_c_vm_generator_wsl(tmpdir, candidate)
            else:
                ok = run_c_vm_generator_posix(tmpdir, candidate)
        except (OSError, subprocess.SubprocessError):
            ok = False
        if not ok:
            return False
        OUT.write_text(candidate.read_text(encoding="utf-8"), encoding="utf-8")
        return True


def main():
    used_c_vm = generate_with_c_vm()
    if used_c_vm:
        bytecode = json.loads(OUT.read_text(encoding="utf-8"))
        source = "C VM"
    else:
        bytecode = generate_with_python()
        source = "Python fallback"
    print(f"wrote {OUT.relative_to(ROOT)} via {source}")
    print(f"{len(bytecode['constants'])} constants, {len(bytecode['instructions'])} instructions")


if __name__ == "__main__":
    main()
